[project]
name = "semantic-steganographic-encoder"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "nltk>=3.9.2",
    "requests>=2.32.5",
]
